#!/bin/sh

set -e

cd "$(dirname "$0")/.."

script/update

echo "==> Running format checks…"
node_modules/.bin/prettier -c **/*.md **/*.js **/*.json --prose-wrap always

echo "==> Validating test fixture JSON…"
node_modules/.bin/ajv -s test/data.schema.json -d test/fixtures.json

echo "==> Running unit tests…"
npm test

echo "==> Validating production JSON…"
node_modules/.bin/ajv -s test/data.schema.json -d data.json

echo "==> Checking expected files exist…"
bin/check-files.js
